-- Updates the Croatian Advisory service page payload for the new /savjetovanje structure.
-- Safe to run on MySQL/MariaDB live after deploying the matching code.

START TRANSACTION;

UPDATE content_service_page_translations AS t
JOIN (
    SELECT id
    FROM content_service_pages
    WHERE template_key = 'advisory'
    ORDER BY CASE WHEN code = 'advisory' THEN 0 ELSE 1 END, sort_order, id
    LIMIT 1
) AS p ON p.id = t.service_page_id
SET
    t.meta_title = 'Savjetovanje',
    t.payload = JSON_SET(COALESCE(t.payload, JSON_OBJECT()),
        '$.hero', JSON_EXTRACT('{"brand_title":"ALPHA CAPITALIS","subtitle_lead":"Savjetovanje","subtitle_accent":"","intro":"Savjetovanje (Advisory) pruža stručnu podršku društvima, investitorima i poduzetnicima u donošenju financijskih i strateških odluka te stvaranju dugoročne vrijednosti.","cta_label":"","cta_url":""}', '$'),
        '$.overview', JSON_EXTRACT('{"kicker":"ŠTO JE SAVJETOVANJE?","title":"Što je savjetovanje?","body":["Savjetovanje (Advisory) pruža stručnu podršku društvima, investitorima i poduzetnicima u donošenju strateških financijskih odluka kroz usluge spajanja i preuzimanja, procjene vrijednosti, dubinska snimanja, pribavljanje kapitala i financijsko restrukturiranje, s ciljem upravljanja rizicima i stvaranja dugoročne vrijednosti."]}', '$'),
        '$.services_intro', JSON_EXTRACT('{"kicker":"USLUGE SAVJETOVANJA","title":"Usluge savjetovanja","intro":""}', '$'),
        '$.service_cards', JSON_EXTRACT('[{"title":"Pribavljanje financiranja","text":"Podrška u strukturiranju i pribavljanju bankovnog financiranja, EU bespovratnih sredstava, poticajnih kredita i private equity kapitala.","url":"/savjetovanje/pribavljanje-financiranja"},{"title":"M&A savjetovanje","text":"Podrška u procesima spajanja i preuzimanja — od strateškog pozicioniranja do pregovaranja i zatvaranja transakcije.","url":"/savjetovanje/prodaja-i-kupnja-poduzeca"},{"title":"Dubinska snimanja (Due Diligence)","text":"Detaljna analiza poslovanja društva radi jasnog uvida u financijsko stanje, rizike i prilike prije važnih odluka ili transakcija.","url":"/savjetovanje/dubinska-snimanja"},{"title":"Procjena vrijednosti društva","text":"Procjena ekonomske vrijednosti društva kao podloga za prodaju, kupnju, dokapitalizaciju i druge strateške aktivnosti.","url":"/savjetovanje/procjena-vrijednosti-drustva"},{"title":"Porezno savjetovanje","text":"Podrška u poreznom planiranju, usklađenosti, poreznim pregledima, transfernim cijenama, poreznim nadzorima i transakcijama.","url":"/savjetovanje/porezno-savjetovanje"}]', '$'),
        '$.funding', JSON_EXTRACT('{"title":"Pribavljanje financiranja","intro":"Pribavljanje financiranja obuhvaća podršku društvima u pronalasku odgovarajućih izvora kapitala za rast poslovanja, investicije i ostvarenje strateških ciljeva.","cards":[{"title":"EU fondovi","text":"EU bespovratna sredstva, nacionalni instrumenti potpore i projektna podrška od identifikacije poziva do provedbe.","url":"/eu-fondovi"},{"title":"Bankovni krediti","text":"Strukturiranje kreditnih zahtjeva i podrška u pregovorima s financijskim institucijama.","url":"/savjetovanje/pribavljanje-financiranja/bankovni-krediti"},{"title":"Zakon o poticanju ulaganja","text":"Podrška u korištenju poreznih olakšica i poticaja za investicijske projekte temeljem ZoPU-a.","url":"/savjetovanje/pribavljanje-financiranja/zakon-o-poticanju-ulaganja"}],"overview_title":"EU fondovi","overview_body":["EU fondovi su instrumenti financiranja kojima Europska unija podupire razvoj poduzetništva, inovacija, digitalne i zelene tranzicije te infrastrukture. Poduzetnicima su na raspolaganju bespovratna sredstva iz Višegodišnjeg financijskog okvira 2021.–2027., a uz EU programe dostupni su i nacionalni instrumenti potpore — HBOR krediti, HAMAG zajmovi te porezne olakšice temeljem Zakona o poticanju ulaganja i istraživačko-razvojnim projektima."],"services_title":"Usluge EU fondova","services":[{"title":"Analiza i odabir natječaja","text":"Analiziramo vaše investicijske i razvojne prioritete te ih povezujemo s odgovarajućim natječajima, kreditnim linijama i instrumentima potpore."},{"title":"Izrada projektne prijave","text":"Pripremamo projektnu logiku, proračun, obrasce i svu prateću dokumentaciju potrebnu za kvalitetnu i pravodobnu prijavu."},{"title":"Provedba i koordinacija projekta","text":"Nakon odobrenja sredstava preuzimamo administrativno praćenje, komunikaciju s tijelima, izvještavanje i projektnu koordinaciju."},{"title":"Financijski instrumenti","text":"Savjetujemo o HBOR kreditima, HAMAG zajmovima i ostalim instrumentima koji mogu biti komplementarni bespovratnim sredstvima."},{"title":"Zakonski poticaji i olakšice","text":"Pomažemo pri korištenju Zakona o poticanju ulaganja, Uredbe o turizmu i Zakona o državnoj potpori za istraživačko-razvojne projekte."},{"title":"Praćenje natječaja","text":"Kontinuirano pratimo nove pozive i pravovremeno vas obavještavamo o prilikama relevantnim za vaše poslovanje."}],"advisory_cards":[]}', '$'),
        '$.bank_loans', JSON_EXTRACT('{"title":"Bankovni krediti","kicker":"BANKOVNI KREDITI","overview_title":"Što su bankovni krediti?","overview_body":["Bankovni krediti predstavljaju jedan od najčešćih izvora financiranja poslovanja, investicija i razvoja društava. Omogućuju poduzetnicima i društvima osiguravanje potrebnih sredstava za rast, povećanje kapaciteta, financiranje projekata ili optimizaciju postojeće financijske strukture."],"services_title":"Naše usluge","services_body":["Pružamo podršku klijentima u procesu pribavljanja bankovnog financiranja, od analize financijskih potreba i pripreme dokumentacije do komunikacije s financijskim institucijama. Naš pristup usmjeren je na pronalazak optimalnih kreditnih rješenja koja odgovaraju poslovnim ciljevima i financijskim mogućnostima klijenta."],"help_title":"U okviru usluge pomažemo u:","help_items":["analizi potreba za financiranjem","pripremi financijskih projekcija i investicijskih podloga","strukturiranju kreditnog zahtjeva","komunikaciji i pregovorima s bankama","analizi uvjeta financiranja","odabiru najpovoljnije strukture kredita"],"approach_title":"Naš pristup","approach_body":["Proces započinjemo detaljnom analizom poslovanja, postojećih obveza i planova razvoja društva. Na temelju razumijevanja poslovnog modela pripremamo kvalitetne financijske materijale i podržavamo klijenta kroz cijeli proces financiranja, s ciljem osiguranja održivog i učinkovitog kreditnog rješenja."]}', '$'),
        '$.zopu', JSON_EXTRACT('{"title":"Zakon o poticanju ulaganja","kicker":"ZAKON O POTICANJU ULAGANJA","overview_title":"Što je Zakon o poticanju ulaganja?","overview_body":["Zakon o poticanju ulaganja predstavlja okvir za korištenje dostupnih potpora namijenjenih poticanju investicija, otvaranju novih radnih mjesta i povećanju konkurentnosti društava. Kroz različite oblike potpora omogućuje se smanjenje troškova ulaganja i stvaranje povoljnijih uvjeta za razvoj poslovanja."],"services_title":"Naše usluge","services_body":["Pružamo stručnu podršku društvima u pripremi i provedbi investicijskih projekata koji mogu ostvariti pravo na potpore prema Zakonu o poticanju ulaganja. Naš pristup obuhvaća analizu prihvatljivosti projekta, pripremu potrebne dokumentacije te podršku kroz cijeli proces realizacije ulaganja."],"help_title":"U okviru usluge pomažemo u:","help_items":["analizi mogućnosti korištenja potpora","procjeni prihvatljivosti investicijskog projekta","pripremi investicijske dokumentacije i prijavne dokumentacije","definiranju ključnih pokazatelja ulaganja","komunikaciji s nadležnim institucijama","praćenju provedbe investicijskih aktivnosti"],"approach_title":"Naš pristup","approach_body":["Proces započinjemo razumijevanjem poslovnih ciljeva klijenta i planirane investicije. Analiziramo potencijalne mogućnosti ostvarivanja potpora te strukturiramo projekt na način koji omogućuje učinkovitu provedbu ulaganja i dugoročnu poslovnu vrijednost."]}', '$'),
        '$.ma', JSON_EXTRACT('{"title":"Prodaja i kupnja poduzeća (M&A)","kicker":"M&A SAVJETOVANJE","overview_title":"Što je prodaja i kupnja poduzeća?","overview_body":["Prodaja i kupnja poduzeća predstavljaju složene poslovne procese koji uključuju prijenos vlasništva, pronalazak odgovarajućih partnera i strukturiranje transakcije s ciljem ostvarivanja optimalne vrijednosti za sve uključene strane."],"show_pandea":true,"services_title":"Naše usluge","services_body":["Pružamo stručnu podršku vlasnicima i investitorima kroz cijeli proces prodaje ili kupnje poduzeća – od početne analize i pripreme transakcije do pregovora i zaključenja posla. Naš pristup usmjeren je na učinkovito upravljanje procesom, zaštitu interesa klijenta i ostvarenje najboljih mogućih uvjeta transakcije."],"help_title":"U okviru usluge pomažemo u:","help_items":["analizi poslovanja i pripremi društva za prodaju","procjeni vrijednosti poduzeća","strukturiranju transakcije","pripremi transakcijske dokumentacije","identifikaciji potencijalnih kupaca ili investitora","analizi ciljanih društava za akviziciju","podršci tijekom dubinskog snimanja i pregovora","pripremi i provedbi procesa zaključenja transakcije"],"approach_title":"Naš pristup","approach_body":["Proces započinjemo razumijevanjem ciljeva vlasnika ili investitora te analizom financijskog i poslovnog položaja društva. Kroz strukturirani proces, financijsku analizu i koordinaciju svih aktivnosti pomažemo klijentima donijeti informirane odluke i uspješno realizirati transakciju."]}', '$'),
        '$.valuations', JSON_EXTRACT('{"title":"Procjena vrijednosti društva","kicker":"PROCJENA VRIJEDNOSTI","overview_title":"Što je procjena vrijednosti?","overview_body":["Procjena vrijednosti predstavlja proces utvrđivanja ekonomske vrijednosti društva na temelju analize poslovanja, financijskih rezultata, tržišnih uvjeta i budućeg potencijala rasta. Koristi se kao podloga za donošenje odluka u procesima prodaje, kupnje, dokapitalizacije i drugih strateških aktivnosti."],"services_title":"Naše usluge","services_body":["Pružamo usluge procjene vrijednosti trgovačkih društava vlasnicima, investitorima i financijskim institucijama, prilagođavajući pristup svrsi i specifičnostima svakog pojedinog projekta. Naš cilj je pružiti objektivan i pouzdan uvid u vrijednost društva te ključne čimbenike koji na nju utječu."],"help_title":"U okviru usluge pomažemo u:","help_items":["analizi poslovanja i financijskih pokazatelja društva","izradi financijskih modela i projekcija","procjeni budućih novčanih tokova i potencijala rasta","primjeni odgovarajućih metoda vrednovanja","podršci kod prodaje društva, akvizicija i dokapitalizacija","pružanju stručne podloge za pregovore i strateške odluke"],"approach_title":"Naš pristup","approach_body":["Proces započinjemo razumijevanjem poslovnog modela, financijske pozicije i cilja procjene. Primjenom relevantnih tržišnih metoda vrednovanja, uključujući metodu diskontiranih novčanih tokova, usporedivih transakcija i usporedivih društava, izrađujemo procjenu koja pruža jasnu osnovu za donošenje kvalitetnih poslovnih odluka."]}', '$'),
        '$.due_diligence', JSON_EXTRACT('{"title":"Dubinska snimanja (Due Diligence)","kicker":"DUE DILIGENCE","overview_title":"Što je dubinsko snimanje (Due Diligence)?","overview_body":["Dubinsko snimanje predstavlja detaljnu analizu poslovanja društva s ciljem dobivanja jasnog i objektivnog uvida u financijsko stanje, poslovne rizike i potencijalnu vrijednost društva prije donošenja važnih poslovnih odluka ili provedbe transakcije."],"services_title":"Naše usluge","services_body":["Pružamo usluge dubinskog snimanja kupcima, prodavateljima i investitorima u procesima spajanja, preuzimanja i drugih poslovnih transakcija. Naš pristup usmjeren je na prepoznavanje ključnih čimbenika koji utječu na vrijednost društva te pravovremeno identificiranje rizika i prilika."],"help_title":"U okviru usluge pomažemo u:","help_items":["analizi financijskih rezultata i poslovanja društva","procjeni održivosti ostvarenih rezultata","identifikaciji ključnih rizika i potencijalnih nepravilnosti","analizi ključnih pokazatelja uspješnosti (KPI)","razumijevanju poslovnog modela i tržišnog položaja","prepoznavanju područja za unapređenje i stvaranje dodatne vrijednosti"],"approach_title":"Naš pristup","approach_body":["Proces započinjemo detaljnom analizom dostupnih financijskih i poslovnih podataka. Kroz strukturirani pristup i razumijevanje poslovanja društva pružamo pouzdanu podlogu za donošenje informiranih odluka, smanjenje rizika i uspješnu realizaciju poslovnih ciljeva."]}', '$'),
        '$.tax', JSON_EXTRACT('{"title":"Porezno savjetovanje","kicker":"POREZNO SAVJETOVANJE","overview_title":"Što je porezno savjetovanje?","overview_body":["Porezno savjetovanje obuhvaća stručnu podršku u razumijevanju i upravljanju poreznim obvezama, procjeni poreznih rizika i donošenju poslovnih odluka usklađenih s važećim propisima. Cilj je osigurati poreznu učinkovitost, usklađenost poslovanja i dugoročnu održivost."],"services_title":"Naše usluge","services_body":["Pružamo porezno savjetovanje pravnim i fizičkim osobama kroz analizu porezne pozicije, planiranje poslovnih aktivnosti i podršku u svakodnevnim poreznim pitanjima, kao i kod složenijih poslovnih transakcija. Naš pristup temelji se na povezivanju poreznih propisa, poslovnih ciljeva i praktične primjene."],"help_title":"U okviru usluge pomažemo u:","help_items":["poreznom planiranju i optimizaciji","analizi poreznih rizika i usklađenosti poslovanja","pripremi poreznih mišljenja i stručnih tumačenja","podršci kod poreznih nadzora","PDV savjetovanju i međunarodnim poreznim pitanjima","transfernim cijenama i povezanim transakcijama","poreznom savjetovanju kod poslovnih restrukturiranja i M&A transakcija"],"approach_title":"Naš pristup","approach_body":["Svaki angažman započinjemo razumijevanjem poslovnog modela, financijske i porezne pozicije klijenta te specifičnih poslovnih okolnosti. Analiziramo relevantne propise i poreznu praksu kako bismo preporučili rješenja koja su zakonita, praktično provediva i usmjerena na smanjenje rizika te stvaranje dugoročne vrijednosti."]}', '$'),
        '$.approach', JSON_EXTRACT('{"kicker":"NAŠ PRISTUP","title":"Naš pristup","body":["Svaki savjetodavni angažman započinjemo razumijevanjem poslovnog konteksta, ciljeva i ključnih rizika. Analiziramo financijske podatke, tržišni položaj, porezne i regulatorne okolnosti te specifičnosti projekta kako bismo predložili rješenja koja su jasna, provediva i usmjerena na stvaranje dugoročne vrijednosti.","Naš pristup spaja strateško razmišljanje i praktičnu provedbu — od početne analize do konkretnih odluka, dokumentacije, komunikacije s dionicima i provedbe projekta."]}', '$'),
        '$.meeting', JSON_EXTRACT('{"kicker":"KONTAKT","title":"Razgovarajmo o vašim poslovnim odlukama","intro":"Javite nam se i zajedno ćemo procijeniti koji oblik savjetodavne podrške najbolje odgovara vašim ciljevima, fazi poslovanja i konkretnom izazovu.","contact_title":"Kontaktirajte nas"}', '$'),
        '$.blog_section', JSON_EXTRACT('{"kicker":"OBJAVE","title":"Savjetovanje","intro":"Zadnje objave i novosti iz područja financija, poreza, transakcija i savjetovanja."}', '$')
    ),
    t.updated_at = NOW()
WHERE t.locale = 'hr';

SET @ac_advisory_batch := (SELECT COALESCE(MAX(batch), 0) + 1 FROM migrations);

INSERT INTO migrations (migration, batch)
SELECT '2026_06_23_090000_update_advisory_service_page_copy', @ac_advisory_batch
WHERE NOT EXISTS (SELECT 1 FROM migrations WHERE migration = '2026_06_23_090000_update_advisory_service_page_copy');

INSERT INTO migrations (migration, batch)
SELECT '2026_06_23_100000_restructure_advisory_service_pages', @ac_advisory_batch
WHERE NOT EXISTS (SELECT 1 FROM migrations WHERE migration = '2026_06_23_100000_restructure_advisory_service_pages');

COMMIT;
