<?php

return [
    'abilities' => [
        ['name' => 'admin.access', 'title' => 'Access admin panel', 'group' => 'system'],
        ['name' => 'dashboard.view', 'title' => 'View dashboard', 'group' => 'dashboard'],

        ['name' => 'catalog.categories.view', 'title' => 'View categories', 'group' => 'catalog.categories'],
        ['name' => 'catalog.categories.create', 'title' => 'Create categories', 'group' => 'catalog.categories'],
        ['name' => 'catalog.categories.update', 'title' => 'Update categories', 'group' => 'catalog.categories'],
        ['name' => 'catalog.categories.delete', 'title' => 'Delete categories', 'group' => 'catalog.categories'],

        ['name' => 'content.blog.view', 'title' => 'View blog posts', 'group' => 'content.blog'],
        ['name' => 'content.blog.create', 'title' => 'Create blog posts', 'group' => 'content.blog'],
        ['name' => 'content.blog.update', 'title' => 'Update blog posts', 'group' => 'content.blog'],
        ['name' => 'content.blog.delete', 'title' => 'Delete blog posts', 'group' => 'content.blog'],

        ['name' => 'content.team.view', 'title' => 'View team members', 'group' => 'content.team'],
        ['name' => 'content.team.create', 'title' => 'Create team members', 'group' => 'content.team'],
        ['name' => 'content.team.update', 'title' => 'Update team members', 'group' => 'content.team'],
        ['name' => 'content.team.delete', 'title' => 'Delete team members', 'group' => 'content.team'],

        ['name' => 'content.glossary.view', 'title' => 'View glossary terms', 'group' => 'content.glossary'],
        ['name' => 'content.glossary.create', 'title' => 'Create glossary terms', 'group' => 'content.glossary'],
        ['name' => 'content.glossary.update', 'title' => 'Update glossary terms', 'group' => 'content.glossary'],
        ['name' => 'content.glossary.delete', 'title' => 'Delete glossary terms', 'group' => 'content.glossary'],

        ['name' => 'content.pages.view', 'title' => 'View info pages', 'group' => 'content.pages'],
        ['name' => 'content.pages.create', 'title' => 'Create info pages', 'group' => 'content.pages'],
        ['name' => 'content.pages.update', 'title' => 'Update info pages', 'group' => 'content.pages'],
        ['name' => 'content.pages.delete', 'title' => 'Delete info pages', 'group' => 'content.pages'],

        ['name' => 'content.services.view', 'title' => 'View service pages', 'group' => 'content.services'],
        ['name' => 'content.services.create', 'title' => 'Create service pages', 'group' => 'content.services'],
        ['name' => 'content.services.update', 'title' => 'Update service pages', 'group' => 'content.services'],
        ['name' => 'content.services.delete', 'title' => 'Delete service pages', 'group' => 'content.services'],

        ['name' => 'content.faqs.view', 'title' => 'View FAQs', 'group' => 'content.faqs'],
        ['name' => 'content.faqs.create', 'title' => 'Create FAQs', 'group' => 'content.faqs'],
        ['name' => 'content.faqs.update', 'title' => 'Update FAQs', 'group' => 'content.faqs'],
        ['name' => 'content.faqs.delete', 'title' => 'Delete FAQs', 'group' => 'content.faqs'],

        ['name' => 'content.comments.view', 'title' => 'View comments', 'group' => 'content.comments'],
        ['name' => 'content.comments.moderate', 'title' => 'Moderate comments', 'group' => 'content.comments'],
        ['name' => 'content.comments.delete', 'title' => 'Delete comments', 'group' => 'content.comments'],

        ['name' => 'content.blocks.view', 'title' => 'View content blocks', 'group' => 'content.blocks'],
        ['name' => 'content.blocks.create', 'title' => 'Create content blocks', 'group' => 'content.blocks'],
        ['name' => 'content.blocks.update', 'title' => 'Update content blocks', 'group' => 'content.blocks'],
        ['name' => 'content.blocks.delete', 'title' => 'Delete content blocks', 'group' => 'content.blocks'],

        ['name' => 'content.navigation.view', 'title' => 'View main navigation setup', 'group' => 'content.navigation'],
        ['name' => 'content.navigation.update', 'title' => 'Update main navigation setup', 'group' => 'content.navigation'],

        ['name' => 'content.slots.view', 'title' => 'View content slots', 'group' => 'content.slots'],
        ['name' => 'content.slots.create', 'title' => 'Create content slots', 'group' => 'content.slots'],
        ['name' => 'content.slots.update', 'title' => 'Update content slots', 'group' => 'content.slots'],
        ['name' => 'content.slots.delete', 'title' => 'Delete content slots', 'group' => 'content.slots'],

        ['name' => 'messages.career.view', 'title' => 'View career applications', 'group' => 'messages.career'],
        ['name' => 'messages.career.moderate', 'title' => 'Moderate career applications', 'group' => 'messages.career'],
        ['name' => 'messages.download_requests.view', 'title' => 'View resource download requests', 'group' => 'messages.download_requests'],
        ['name' => 'messages.download_requests.moderate', 'title' => 'Moderate resource download requests', 'group' => 'messages.download_requests'],

        ['name' => 'media.manage', 'title' => 'Manage media', 'group' => 'content.media'],

        ['name' => 'users.list.view', 'title' => 'View users', 'group' => 'users.core'],
        ['name' => 'users.profile.update', 'title' => 'Update user profiles', 'group' => 'users.core'],
        ['name' => 'users.access.manage', 'title' => 'Manage roles & abilities', 'group' => 'users.access'],

        ['name' => 'settings.system.runtime.manage', 'title' => 'Manage runtime controls', 'group' => 'settings.system'],
        ['name' => 'settings.system.admin_appearance.manage', 'title' => 'Manage admin appearance settings', 'group' => 'settings.system'],
        ['name' => 'settings.system.store.manage', 'title' => 'Manage store settings', 'group' => 'settings.system'],
        ['name' => 'settings.local.languages.manage', 'title' => 'Manage languages', 'group' => 'settings.local'],
        ['name' => 'settings.user.manage', 'title' => 'Manage user settings', 'group' => 'settings.user'],

        ['name' => 'ai.admin.use', 'title' => 'Use admin AI assistant', 'group' => 'system.ai'],
    ],

    'roles' => [
        'admin' => [
            'admin.access',
            'dashboard.view',
            'catalog.categories.view',
            'catalog.categories.create',
            'catalog.categories.update',
            'catalog.categories.delete',
            'content.blog.view',
            'content.blog.create',
            'content.blog.update',
            'content.blog.delete',
            'content.team.view',
            'content.team.create',
            'content.team.update',
            'content.team.delete',
            'content.glossary.view',
            'content.glossary.create',
            'content.glossary.update',
            'content.glossary.delete',
            'content.pages.view',
            'content.pages.create',
            'content.pages.update',
            'content.pages.delete',
            'content.services.view',
            'content.services.create',
            'content.services.update',
            'content.services.delete',
            'content.faqs.view',
            'content.faqs.create',
            'content.faqs.update',
            'content.faqs.delete',
            'content.comments.view',
            'content.comments.moderate',
            'content.comments.delete',
            'content.blocks.view',
            'content.blocks.create',
            'content.blocks.update',
            'content.blocks.delete',
            'content.navigation.view',
            'content.navigation.update',
            'content.slots.view',
            'content.slots.create',
            'content.slots.update',
            'content.slots.delete',
            'messages.career.view',
            'messages.career.moderate',
            'messages.download_requests.view',
            'messages.download_requests.moderate',
            'media.manage',
            'users.list.view',
            'users.profile.update',
            'settings.system.runtime.manage',
            'settings.system.admin_appearance.manage',
            'settings.system.store.manage',
            'settings.local.languages.manage',
            'settings.user.manage',
            'ai.admin.use',
        ],
        'editor' => [
            'admin.access',
            'dashboard.view',
            'catalog.categories.view',
            'catalog.categories.update',
            'content.blog.view',
            'content.blog.create',
            'content.blog.update',
            'content.team.view',
            'content.team.create',
            'content.team.update',
            'content.glossary.view',
            'content.glossary.create',
            'content.glossary.update',
            'content.pages.view',
            'content.pages.create',
            'content.pages.update',
            'content.services.view',
            'content.services.create',
            'content.services.update',
            'content.faqs.view',
            'content.faqs.create',
            'content.faqs.update',
            'content.comments.view',
            'content.comments.moderate',
            'content.blocks.view',
            'content.blocks.create',
            'content.blocks.update',
            'content.navigation.view',
            'content.navigation.update',
            'content.slots.view',
            'content.slots.create',
            'content.slots.update',
            'media.manage',
        ],
        'customer' => [],
    ],
];
